menu:
  主页: /
  归档: /archives
  关于我: /about
  标签: /tags


# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:

avatar: "http://7xt53g.com2.z0.glb.clouddn.com/carton.jpg"
